site_name: Paykit
site_url: https://paykit-sdk.github.io/paykit
repo_url: https://github.com/paykit-sdk/python-core
repo_name: paykit-sdk/python-core
watch: [mkdocs.yaml, README.md]

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            docstring_style: google
            merge_init_into_class: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]

nav:
  - Home: index.md
  - Usage:
      - Python:
          - Django:
              - Payme: usage/python/django/payme.md
              - Code layout: usage/python/django/clayout.md
