# Generated by Django 5.2.15 on 2026-06-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('merchant_key', models.CharField(max_length=255, unique=True)),
                ('merchant_secret', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('amount', models.BigIntegerField(help_text='Amount in tiyins')),
                ('order_id', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='inactive', max_length=20)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payme.paymemerchant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, unique=True)),
                ('payme_time', models.BigIntegerField()),
                ('order_id', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Performed'), (-1, 'Cancelled'), (-2, 'Cancelled after perform')], default=1)),
                ('reason', models.IntegerField(blank=True, choices=[(1, 'Receiver not found'), (2, 'Debit failed'), (3, 'Execution failed'), (4, 'Cancelled by timeout'), (5, 'Fund returned'), (10, 'Unknown')], null=True)),
                ('create_time', models.BigIntegerField(blank=True, null=True)),
                ('perform_time', models.BigIntegerField(blank=True, null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(default=dict)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payme.paymemerchant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=255, unique=True)),
                ('state', models.IntegerField()),
                ('type', models.IntegerField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('paid_at', models.BigIntegerField(blank=True, null=True)),
                ('cancelled_at', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payme.paymetransaction')),
            ],
        ),
    ]
