name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # triggers on tags like v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: paykit

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: pip install build twine

      - name: Build
        run: python -m build paykit/

      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
